### ISSUE TITLE
Nunjucks Style Comments

### ISSUE THREAD

**Issue by ngblaylock** [edheltzel/nunjucks-for-visual-studio-code#1]
First and foremost, thank you for making a good Nunjucks extension that works for Eleventy. In the little amount of time that I have used it it has been great. 

The only thing I can see that is missing is nunjucks style comments. In VS Code when you hit `ctrl + /` or `cmd + /` you still get the HTML formatted comments (`<!-- -->`). It would be nice to get the nunjucks style comments (`{# #}`).

**Comment by edheltzel** [comment]
Good catch... I'll add it to my `to-dos`.

**Comment by edheltzel** [comment]
@ngblaylock I just created a [release `v0.2.0`](https://github.com/edheltzel/nunjucks-for-visual-studio-code/releases/tag/v0.2.0) which adds support for Nunjucks comment using the `ctrl + /` or `cmd + /`

I will also note that I added a snippet for adding an HTML comment: `hcomm` but I think a better solution would be to add  a keybinding to Emmet: Toggle Comment – I suggest using `ctrl+alt+/`

```json
{
  "key": "ctrl+alt+/",
  "command": "editor.emmet.action.toggleComment"
}
```

**Comment by ngblaylock** [comment]
Perfect! Just what I was hoping for, and very quick turnaround. Thanks @edheltzel.

**Comment by edheltzel** [comment]
> Not sure if I misconfigured something here, but for me it also changed the comments in html files to nunjucks comments.
> 
> Is that a bug, or a misconfiguration on my side?


If you want HTML comments you'll need to use the snippet or you can add the custom key binding for Emmet to insert HTML comments.

If you are using `ctrl+/` or `cmd+/` that will I sert nunjucks comments.

**Comment by edheltzel** [comment]
> ok, would probably make sense to only change the comment output for nunjucks files, and keep the normal html comment format for html files. Or at least make this override optional.
> 
> (i'm using `cmd+/` and would like to keep it that way for all my files (html, js etc.), not make a new keybinding just to avoid the nunjucks comment format in html files)


I completely agree... But the challenge would be to figuring out what comment should be nunjucks or HTML based on the keyboard command `cmd+/`, which is why I suggested using the keyboard command for Emmet.

I'd be happy to merge any PR if you have a solution?

**Comment by ngblaylock** [comment]
Two thoughts
1. If the project isn't a Nunjucks project, you could just disable the plugin for the workspace.
2. The plugin by default also takes over .html files by default. Could there be a setting to disable .html/.md and only handle .njk files? I don't know what side effects that could have.

**Comment by edheltzel** [comment]
> as far as i'm aware, html comments are still valid in nunjucks files, whereas nunjucks comments are not seen as comments in html files. this alone should warrant a switch in the logic in my opinion: keep the default keybind and make the nunjucks comment keybind manual/optional.
> 
> a nunjucks extension should not break the default html behaviour in html files without the user making it that way intentionally. 
> 
> what @ngblaylock said in point 2 would make the most sense to me.

We can definitely explore the options here, but I do agree default HTML behavior should take priority in HTML files.
