### ISSUE TITLE
renderTemplate snippet opening tag is output as "renderTemplatender"

### ISSUE THREAD

**Issue by mjawn** [edheltzel/nunjucks-for-visual-studio-code#12]
Here's the typo:

https://github.com/edheltzel/nunjucks-for-visual-studio-code/blob/ff00b867119aa8c6a0d132d2598d05b0df418a6a/src/snippets/nunjucks-snippets.json#L185

Love this extension, it's the best yet for Nunjucks. Thanks for your work.

**Comment by edheltzel** [comment]
😬 sorry about that.

**Comment by edheltzel** [comment]
just published to the vscode marketplace - generally takes a few minutes for it to be accepted and available to download.

**Comment by mjawn** [comment]
Thanks for the quick turnaround. It wasn't much of a blocker.
