### ISSUE TITLE
property value expected and at-rule or selector expected

### ISSUE THREAD

**Issue by 3rr0r404N07F0UND** [edheltzel/nunjucks-for-visual-studio-code#14]
![제목 없음](https://user-images.githubusercontent.com/117527664/235051177-5767e82a-9a8f-4682-8762-1da8b880d5ca.png)

this is vscode html error

i think this extension can fix this problem

**Comment by edheltzel** [comment]
@3rr0r404N07F0UND - Better Nunjucks doesn't do any validation of code, this is actually handled by the VSCode itself, unless you're using something like Prettier inside of your project. 

If you go to your VSCode setting and search for `html validate` you can turn off the validation, if you do not want this behavior for all projects, then update your workspace settings (see image).


![Screenshot 2023-04-28 at 8 57 16 AM](https://user-images.githubusercontent.com/402910/235154123-39f26d2f-1d78-4b59-8d2c-0cea124ca67d.png)
