### ISSUE TITLE
Formatting Indentation

### ISSUE THREAD

**Issue by codyjoyce** [edheltzel/nunjucks-for-visual-studio-code#15]
Hi, Love the extension as it's the only one that keeps everything working as it is supposed to.

Just wondering if there is a way to enable indentation when using auto format, so my templates appear as so

```
{%
    set foo = "bar"
%}
```

instead of it currently doing
```
{%
set foo = "bar"
%}
```

same goes for {% block foo %} tags also. Hoping you can point me in the right direction

**Comment by edheltzel** [comment]
1. @codyjoyce There is no built-in formatter with the extension... I do recommend [Nunjucks Template Formatter](https://marketplace.visualstudio.com/items?itemName=okitavera.vscode-nunjucks-formatter), which does have a few configuration options, but IDK if it will do what you're asking.
