### ISSUE TITLE
Syntax Highlighting treating md's `---` as Frontmatter

### ISSUE THREAD

**Issue by nitin2953** [edheltzel/nunjucks-for-visual-studio-code#19]
Consider `---` as frontmatter only if it is at the beginning of the file

![image](https://github.com/user-attachments/assets/f868bc45-5e21-4805-b300-c1075ee7d254)

**Update:**
It is treating every even `---` as frontmatter

**Comment by edheltzel** [comment]
let me see what I can do.

**Comment by edheltzel** [comment]
> Update:
It is treating every even --- as frontmatter

@nitin2953 Is this happening only in markdown or in HTML, Nunjucks

**Comment by nitin2953** [comment]
I don't know what is happening here,

**The extension should treat `---` as frontmatter only if it is at the beginning of the file and discard everything after it**

![all files](https://github.com/user-attachments/assets/378a0ee0-332b-4f09-802a-7bf7e787e4d3)

these are my extensions & settings

![Screenshot 2024-07-24 085013_cx](https://github.com/user-attachments/assets/39a41e2a-df04-4ee1-8e8e-bb8e9d44a664)

**Comment by edheltzel** [comment]
Thanks for the screenshots... I don't know of too many use cases where `---` is used outside of the horizontal rule in markdown when it's not being used as frontmatter. That said, I do think it is possible with target-only frontmatter at the beginning of a file versus in the middle.

Let try a few things locally and if I find something I'll share it here for you to add to your workspace settings as a temp solution.
