### ISSUE TITLE
Frontmatter "breaks" extension

### ISSUE THREAD

**Issue by ReduxFlakes** [edheltzel/nunjucks-for-visual-studio-code#21]
So when I woke up today to start working on my website I noticed that all of my `.njk` and `.md` that had frontmatter (`---`) did not have syntax highlighting and snippets did not work.

For some reason having a frontmatter breaks the extension. I tried other extensions related to nunjucks but they seem to work fine, I also tried disabling everything but the issue persists.

Yesterday it was working just fine, this just happened today and I don't know what to do, the only thing I did was shutdown my computer.

I have attached screenshots below to show the issue.

**Nunjucks file without frontmatter showing that the extensions behaves correctly**

![Screenshot 2024-08-02 213157](https://github.com/user-attachments/assets/c9a83694-85be-49c2-9dc6-bb1a681b5f6c)

**Nunjucks file with frontmatter showing that the extensions stops working**

![Screenshot 2024-08-02 213210](https://github.com/user-attachments/assets/5d086d08-9b9f-441b-b109-3690b520d65c)

**The same thing happens with markdown files - in this case without frontmatter and working**

![Screenshot 2024-08-02 213234](https://github.com/user-attachments/assets/f2a0a30c-23f4-41ac-91fe-633c708b5eab)

**and with frontmatter, not working**

![Screenshot 2024-08-02 213223](https://github.com/user-attachments/assets/e7d649e1-1ead-401d-9e73-0db9707f8700)

**Comment by edheltzel** [comment]
Let me see what I can do.

**Comment by edheltzel** [comment]
@ReduxFlakes what version of VSCode are you using? It seems that [July 2024 (version 1.92)](https://code.visualstudio.com/updates/v1_92) release has changed/broken something. 

I hate to ask if you could test this to confirm what I am seeing, but download and rollback your VSCode version to the [June 2024 release](https://code.visualstudio.com/updates/v1_91) and let me know if the results are the same?

**Comment by gasatrya** [comment]
@edheltzel same thing for me and yes, I am currently using the latest version of VS Code.
![image](https://github.com/user-attachments/assets/cc53c9f4-e301-4051-8ae5-c159f1578596)

**Comment by edheltzel** [comment]
If you try downloading vscode v1.91.1 and not update to 1.92 the extension works. 

I tested both versions of vscode with better nunjucks v0.2.72 and v.0.60. 

In vscode 1.91.1 both BN v0.2.72 & v0.2.6 work as expected. 

In vscode 1.92 both are broken 

---

Ref: https://github.com/microsoft/vscode/issues/224680

**Comment by ReduxFlakes** [comment]
@edheltzel I am using the latest. I will try rolling back to see, I didn't noticed VS Code had updated since I have the "new release" tab disabled.

**Comment by ReduxFlakes** [comment]
@gasatrya yes that's the same issue I have, in my case I'm using Gruvbox and everything turns green, another interesting issue is when I have the char # anywhere, everything after it turns red .

**Comment by RedCMD** [comment]
Nunjucks is using an outdated FrontMatter include

The FrontMatter integration should be updated to match Markdowns

https://github.com/edheltzel/nunjucks-for-visual-studio-code/blob/05196ca36343d76af521f1dd0b7da894c7c95963/src/syntaxes/nunjucks.tmLanguage.json#L123-L139

https://github.com/microsoft/vscode-markdown-tm-grammar/pull/162

https://github.com/microsoft/vscode-markdown-tm-grammar/blob/main/markdown.tmLanguage.base.yaml#L202-L216

**Comment by edheltzel** [comment]
@RedCMD This is very close... it resolves the syntax highlighting for nunjucks, but breaks the frontmatter syntax highlighting.

**Comment by ReduxFlakes** [comment]
@edheltzel can confirm that the new 0.3.0 release fixes the issue on the latest version of VS Code, thanks!

**Comment by gasatrya** [comment]
Wow, that was fast! @edheltzel and thanks @RedCMD
