### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by michael-proulx** [edheltzel/nunjucks-for-visual-studio-code#4]
Very good plugin, I found an issue for specific file configuration with 11ty.

I'm using the before callback for a specific file, because I need to filter my variable for localisation, normally I do not need that, because I do create page in every languages.

But using ---js broke syntax highlighting but it is required for 11ty (https://www.11ty.dev/docs/pagination/#the-before-callback)

https://user-images.githubusercontent.com/23478544/173084613-3f14d43d-a957-4af3-8cc7-f7249d63f604.mp4

**Comment by edheltzel** [comment]
@michael-proulx That's interesting... I'm assuming the file extension is either `html` or `njk` ?

**Comment by michael-proulx** [comment]
Yes it's index.njk

**Comment by edheltzel** [comment]
@michael-proulx 

I have a working modification that extends the YAML support so the highlighting does not break.

As of right now, this is more of a workaround, since I just included some regex to accommodate the [11ty's custom frontmatter](https://www.11ty.dev/docs/data-frontmatter-customize). 

https://user-images.githubusercontent.com/402910/173113811-3b239081-0634-4425-ba84-3f39f12d608b.mp4

**Comment by edheltzel** [comment]
@michael-proulx 
I'll do some more research on how to add additional syntax highlighting for embedded grammars like `json`/`toml`/`js` but right now I don't know if there is a way to do this inside of frontmatter.

**Comment by michael-proulx** [comment]
Nice thank you !! :)

**Comment by munael** [comment]
As of the current version, I see something like this:
![image](https://user-images.githubusercontent.com/5769148/193430110-5a39e689-60b2-4a8f-9b97-374f441743a1.png)

When the specified language is HTML: Only the frontmatter has syntax highlighting. (It's a monochrome theme, but still.)

When the specified language is Nunjucks: Highlighting more broken.
![image](https://user-images.githubusercontent.com/5769148/193430153-6228780d-1f22-4541-b15a-d48f1dda47fa.png)

Plus tooltips for HTML tags no longer work. I've added the `emmet` configs mentioned in multiple extensions but can't be sure this's even meant to re0enable tooltips or something else entirely.

**Comment by edheltzel** [comment]
> As of the current version, I see something like this: ![image](https://user-images.githubusercontent.com/5769148/193430110-5a39e689-60b2-4a8f-9b97-374f441743a1.png)
> 
> When the specified language is HTML: Only the frontmatter has syntax highlighting. (It's a monochrome theme, but still.)
> 
> When the specified language is Nunjucks: Highlighting more broken. ![image](https://user-images.githubusercontent.com/5769148/193430153-6228780d-1f22-4541-b15a-d48f1dda47fa.png)
> 
> Plus tooltips for HTML tags no longer work. I've added the `emmet` configs mentioned in multiple extensions but can't be sure this's even meant to re0enable tooltips or something else entirely.

@munael Could you provide me a little more context or the file you're trying to get syntax highlighting working?
