### ISSUE TITLE
No response or How to use with .md file

### ISSUE THREAD

**Issue by hiuxia** [edheltzel/nunjucks-for-visual-studio-code#8]
Sorry to bother for my limited level. After reading the `readme` quite a few times, I still can not figure out how to use this plugin to **highlight, format and use the snippets** for the nunjuck language. 

My usage scenario is to write the `zotero integration` template in `.md` format. Thanks again.

**Comment by edheltzel** [comment]
@hiuxia I'm not familiar  `zotero`, but if you install and enable Better Nunjucks inside of VSCode - all `.md`, `.html`, and `.njk` files will have Nunjucks syntax highlighting and snippets available. So there shouldn't be any need to adjust your VSCode settings...

Also, note, there is no formatting that comes with this extension - I suggest you look at using [Nunjucks Template Formatter](https://marketplace.visualstudio.com/items?itemName=okitavera.vscode-nunjucks-formatter)

**Comment by hiuxia** [comment]
Sorry for the late reply. Now the plugin works pretty well. Maybe there are some **plugin conflicts**(_few markdown plugins?_) after the installation (by the way, there is no `zotero` plugin for `vscode` and I'm using `zotero` with `obsidian` for my research).  

Also, Thanks for this wonderful plugin and the [Nunjucks Template Formatter](https://marketplace.visualstudio.com/items?itemName=okitavera.vscode-nunjucks-formatter) you recommend!
